# Generated by Django 4.0.3 on 2022-03-25 10:54

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program_Type', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Program_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('description', models.TextField()),
                ('level', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermidiate', 'Intermidiate'), ('Pro', 'Pro'), ('All Levels', 'All Levels')], max_length=255)),
                ('status', models.CharField(blank=True, choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=255)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('price', models.IntegerField(blank=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('Program_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='landing.program')),
            ],
        ),
    ]
