# Generated by Django 4.0.3 on 2022-03-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_detail',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
