# Generated by Django 4.0.3 on 2022-03-29 11:05

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_program_detail_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('video_title', models.CharField(blank=True, max_length=1000)),
                ('description', models.TextField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='landing.program_detail')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('file_name', models.CharField(blank=True, max_length=1000)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='landing.program_detail')),
            ],
        ),
    ]
