# Generated by Django 4.0.3 on 2022-03-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_topic_programattachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='video',
        ),
        migrations.AddField(
            model_name='topic',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
