# Generated by Django 4.0.3 on 2022-04-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_alter_programattachments_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterModelOptions(
            name='program_detail',
            options={'verbose_name_plural': 'Program Cards'},
        ),
        migrations.AlterModelOptions(
            name='programattachments',
            options={'verbose_name_plural': 'Program Attachments'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name_plural': 'Program Content'},
        ),
    ]
