# Generated by Django 4.0.3 on 2022-04-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_alter_program_options_alter_program_detail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program_detail',
            options={'verbose_name_plural': 'Add Program Cards'},
        ),
        migrations.AlterModelOptions(
            name='programattachments',
            options={'verbose_name_plural': 'Add Program Attachments'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name_plural': 'Add Program Content'},
        ),
    ]
