# Generated by Django 4.0.3 on 2022-04-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_alter_program_detail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name_plural': 'Add Programs'},
        ),
    ]
