# Generated by Django 4.0.4 on 2022-07-26 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_alter_program_options_alter_program_detail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_detail',
            name='Program_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='landing.program'),
        ),
        migrations.AlterField(
            model_name='programattachments',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='landing.program_detail'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='landing.program_detail'),
        ),
    ]
