# Generated by Django 4.0.3 on 2022-04-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=30)),
                ('contacts', models.TextField()),
                ('gender', models.TextField()),
                ('weight', models.TextField()),
                ('height', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('photos', models.ImageField(upload_to='media_image')),
                ('goals', models.TextField()),
            ],
        ),
    ]
