# Generated by Django 4.0.3 on 2022-04-21 11:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=1000, verbose_name='Full Name')),
                ('contacts', models.CharField(blank=True, max_length=30, verbose_name='Contact')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=30, verbose_name='Gender')),
                ('weight', models.CharField(blank=True, max_length=30, verbose_name='Weight(kgs)')),
                ('height', models.CharField(blank=True, max_length=30, verbose_name='Height(ft)')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='Date of Birth')),
                ('photos', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('goals', models.TextField(blank=True, verbose_name='Goals')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'User Profile',
            },
        ),
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
