# Generated by Django 4.0.4 on 2022-04-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='photos',
            new_name='profilePic',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='height',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='weight',
        ),
    ]
