# Generated by Django 4.0.4 on 2022-04-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_photos_userinfo_profilepic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='profilePic',
        ),
    ]
