# Generated by Django 4.0.4 on 2022-04-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_userinfo_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
