# Generated by Django 4.0.4 on 2022-04-29 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0008_alter_userinfo_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='names',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userinfo',
            constraint=models.UniqueConstraint(fields=('names',), name='unique_case'),
        ),
    ]
