# Generated by Django 4.0.4 on 2022-05-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_workout_gender_workout_hip_workout_waist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='gender',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.userinfo'),
        ),
    ]
