# Generated by Django 4.0.4 on 2022-05-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_workout_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='gender',
        ),
    ]
