# Generated by Django 4.0.4 on 2022-05-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_remove_workout_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='whr',
            field=models.IntegerField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='workout',
            name='whrStatus',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
