# Generated by Django 4.0.4 on 2022-05-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profilePic',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
