# Generated by Django 4.0.4 on 2022-05-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_alter_userinfo_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='contacts',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profilePic',
            field=models.FileField(default='1.png', upload_to='img/'),
        ),
    ]
