# Generated by Django 4.0.4 on 2022-05-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_alter_userinfo_contacts_alter_userinfo_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profilePic',
            field=models.ImageField(default='1.png', upload_to='img/'),
        ),
    ]
