# Generated by Django 4.0.4 on 2022-05-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_alter_userinfo_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.ImageField(default='1.png', upload_to='img/')),
            ],
        ),
    ]
