# Generated by Django 4.0.4 on 2022-05-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
