# Generated by Django 4.0.4 on 2022-05-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='bmi',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='whr',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
