# Generated by Django 4.0.4 on 2022-09-11 17:18

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_alter_workout_bmi_alter_workout_whr'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('adress_line_1', models.CharField(blank=True, max_length=50)),
                ('adress_line_2', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'Female'), ('Other', 'Other')], max_length=25)),
                ('goal', models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Strength', 'Strength'), ('Conditioning', 'Conditioning'), ('Muscle Gain', 'Muscle Gain'), ('Stay Fit', 'Stay Fit'), ('Mobility & Flexibility', 'Mobility & Flexibility'), ('Nutrition/Diet', 'Nutrition/Diet'), ('Other', 'Other')], max_length=50)),
                ('fitness_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Athlete', 'Athlete')], max_length=50)),
                ('number_of_sessions', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
                ('program', models.CharField(choices=[('Bodybuilding', 'Bodybuilding'), ('Weight Lose', 'Weight Lose'), ('Conditioning', 'Conditioning'), ('Strength', 'Strength'), ('Full Body', 'Full Body'), ('Metcon', 'Metcon'), ('Circuit', 'Circuit'), ('Tabata', 'Tabata'), ('Mobility & Flexibility', 'Mobility & Flexibility')], max_length=50)),
                ('personal_coach', models.BooleanField()),
            ],
        ),
    ]
