# Generated by Django 4.0.4 on 2022-09-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_subscriptionplan_subscriptionfeatures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionfeatures',
            options={'verbose_name': 'Subscription Plan Feature', 'verbose_name_plural': 'Subscription Plan Features'},
        ),
        migrations.RemoveField(
            model_name='subscriptionfeatures',
            name='sub_plan',
        ),
        migrations.AddField(
            model_name='subscriptionfeatures',
            name='sub_plan',
            field=models.ManyToManyField(to='customer.subscriptionplan'),
        ),
    ]
