# Generated by Django 4.0.4 on 2022-09-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_alter_subscriptionfeatures_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='highlight_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
