# Generated by Django 4.0.4 on 2022-11-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_personalplan_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='contacts',
            field=models.CharField(blank=True, max_length=30, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=30, verbose_name='Gender'),
        ),
    ]
