# Generated by Django 4.0.4 on 2023-03-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_alter_userinfo_contacts_alter_userinfo_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestyleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(help_text='What do you do for a living?', max_length=512)),
                ('work_hours', models.IntegerField(help_text='How many hours on average do you work each week?\t')),
                ('time_spent_on', models.CharField(choices=[('Standing', 'Standing'), ('Sitting', 'Sitting'), ('Driving', 'Driving'), ('Active', 'Active')], help_text='How do you spend the majority of your time at work?', max_length=60)),
                ('shcedule', models.CharField(help_text='Do you follow a regular working schedule, do you work days, afternoon or nights?', max_length=512)),
                ('wake_up_status', models.CharField(help_text='When you wake up are you ', max_length=512)),
                ('travel', models.CharField(help_text='How often do you travel? ', max_length=100)),
                ('body_weight_status', models.CharField(help_text='How would you consider your current body weight', max_length=100)),
                ('activity_level', models.CharField(help_text='How would you describe your current activity level', max_length=100)),
                ('job_stress_rating', models.IntegerField(help_text='How would you rate the stress of your job?')),
                ('lifestyle_stress_rating', models.IntegerField(help_text='How would you rate the stress of your lifestyle?')),
                ('physical_activities', models.TextField(help_text='Please list the physical activities that you participate in outside of the gym and outside of work.')),
                ('reason_for_Lifestyle_change', models.TextField(help_text='Why have you decided to have a lifestyle review?')),
                ('areas_to_focus_on', models.TextField(help_text='What is the main area that you would like to focus on?')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalActivityReadinessQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_condition', models.BooleanField(help_text='Has your doctor ever said you have a heart condition? ')),
                ('chest_pains', models.BooleanField(help_text='Do you feel pain in your chest at rest, during your daily activities of living, or when you do physical activity?*')),
                ('lost_consciousness_before', models.BooleanField(help_text='Do you lose balance because of dizziness or have you lost consciousness in the last 12 months?*')),
                ('other_medical_condition', models.BooleanField(help_text='Have you ever been diagnosed with another chronic medical condition (other than heart disease or high blood pressure)?*')),
                ('if_yes_explain', models.TextField(blank=True, help_text='If yes to the above question, please list the condition(s) here. ')),
                ('taking_prescribed_medicine', models.BooleanField(help_text='Are you currently taking prescribed medications for a chronic medical condition?*')),
                ('if_yes_list_medicine', models.TextField(blank=True, help_text='If yes to the previous question, please list your medications and how long you have been taking them. ')),
            ],
        ),
    ]
