# Generated by Django 4.0.4 on 2022-09-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
