# Generated by Django 4.0.4 on 2022-07-26 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0014_alter_program_detail_program_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckoutRequestID', models.CharField(max_length=50, null=True, unique=True)),
                ('MerchantRequestID', models.CharField(max_length=30, null=True, unique=True)),
                ('ResultCode', models.IntegerField(null=True)),
                ('mode', models.CharField(blank=True, max_length=40, null=True)),
                ('ResultDescription', models.TextField(max_length=200, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landing.program_detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Initiated Transaction',
                'verbose_name_plural': 'Initiated Transactions',
            },
        ),
    ]
