# Generated by Django 4.0.3 on 2022-03-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_myuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
