# Generated by Django 4.0.4 on 2022-07-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workout_Junction',
            new_name='WorkoutJunction',
        ),
    ]
