# Generated by Django 4.0.4 on 2022-07-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_rename_workout_junction_workoutjunction'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='duration',
            field=models.IntegerField(default=10),
        ),
    ]
