# Generated by Django 4.0.4 on 2022-07-26 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_exercise_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='workouts', to='workouts.programworkout'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.IntegerField(default=10, help_text='Duration in Minutes'),
        ),
        migrations.DeleteModel(
            name='WorkoutJunction',
        ),
    ]
