# Generated by Django 4.0.4 on 2022-07-26 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_remove_exercise_workout_remove_programworkout_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutentry',
            options={'verbose_name_plural': 'Workout Entries'},
        ),
        migrations.AlterField(
            model_name='workoutentry',
            name='mod_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
