# Generated by Django 4.0.4 on 2022-08-26 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_alter_workoutentry_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutentry',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workoutentry',
            name='workout',
        ),
        migrations.AlterModelOptions(
            name='programworkout',
            options={'verbose_name': 'Workout'},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_type',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='video_title',
        ),
        migrations.RemoveField(
            model_name='programworkout',
            name='workout_type',
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('Endurance', 'Endurance'), ('Strength', 'Strength'), ('Balance', 'Balance'), ('Flexibility', 'Flexibility')], default='Balance', max_length=200),
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ManyToManyField(related_name='Exercises', to='workouts.programworkout'),
        ),
        migrations.AddField(
            model_name='programworkout',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=200),
        ),
        migrations.AddField(
            model_name='programworkout',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workouts.programworkout', verbose_name='Workout'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Equipments', to='workouts.equipment'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='videofile',
            field=models.FileField(blank=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.DeleteModel(
            name='ExerciseType',
        ),
        migrations.DeleteModel(
            name='WorkoutEntry',
        ),
        migrations.DeleteModel(
            name='WorkoutType',
        ),
    ]
