# Generated by Django 4.0.4 on 2022-09-07 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_remove_workoutentry_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programworkout',
            name='parent',
        ),
    ]
