# Generated by Django 4.0.4 on 2022-09-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_remove_programworkout_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='programworkout',
            name='slug',
            field=models.SlugField(default=123, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programworkout',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
