# Generated by Django 4.0.4 on 2022-09-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_subscriptionplan_highlight_status'),
        ('workouts', '0009_programworkout_slug_alter_programworkout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programworkout',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.subscriptionplan'),
        ),
    ]
