# Generated by Django 4.0.4 on 2022-10-16 07:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_workoutplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
