# Generated by Django 4.0.4 on 2022-10-18 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0015_workoutplan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
