# Generated by Django 4.0.4 on 2023-03-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_workoutplan_slug_alter_workoutplan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ManyToManyField(related_name='Exercises', to='workouts.programworkout'),
        ),
    ]
